---
- name: Create project folder
  file:
    name: "{{ docker_project_folder }}/grafana/"
    state: directory

- name: Create data folder
  file:
    name: "{{ docker_data_folder }}/grafana/"
    state: directory

- name: Copy env
  template:
    src: env.j2
    dest: "{{ docker_project_folder }}/grafana/.env"

- name: Copy docker-compose
  copy:
    src: docker-compose.yml
    dest: "{{ docker_project_folder }}/grafana/docker-compose.yml"

- name: Start grafana
  docker_service:
    project_src: "{{ docker_project_folder }}/grafana"
    pull: yes
