- name: Start watchtower
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    state: started
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: always