version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:v0.32.1
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=matrix.chaospott.de
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - SYNAPSE_RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - SYNAPSE_RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - SYNAPSE_REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}
      - SYNAPSE_MACAROON_SECRET_KEY=${MACAROON_SECRET_KEY}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/files:/data
      - ${DATA_FOLDER}/uploads:/data/uploads
      - ${DATA_FOLDER}/media:/data/media
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:matrix.chaospott.de
      - traefik.port=8448

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/schemas:/var/lib/postgresql/data