---
- name: Copy env
  template:
    src: env.j2
    dest: "{{ docker_project_folder }}/SpaceApiDaemon/.env"

- name: Copy docker-compose
  copy:
    src: docker-compose.yml
    dest: "{{ docker_project_folder }}/SpaceApiDaemon/docker-compose.yml"

- name: Start SpaceApiDaemon
  docker_service:
    project_src: "{{ docker_project_folder }}/SpaceApiDaemon"
    pull: yes
