version: '3'
services:
  mediawiki:
    image: chaospott/mediawiki
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:wiki.chaospott.de"
    networks:
      - web
      - default
    depends_on:
      - database
    volumes:
      - ${DATA_FOLDER}/images:/usr/share/webapps/mediawiki/images
      - ${DATA_FOLDER}/LocalSettings.php:/usr/share/webapps/mediawiki/LocalSettings.php
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wiki
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ${DATA_FOLDER}/db:/var/lib/mysql

networks:
  web:
    external: true
